require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const prisma = new PrismaClient();
const now = new Date();
const day = (offset = 0, hour = 10) => { const d = new Date(now); d.setDate(d.getDate() + offset); d.setHours(hour, 0, 0, 0); return d; };
const ago = (days, hour = 10) => day(-days, hour);

async function main() {
  const password = process.env.DEMO_PASSWORD || 'Demo@12345';
  const hash = await bcrypt.hash(password, 10);
  const hospital = await prisma.hospital.upsert({
    where: { code: 'CCH-DEMO' },
    update: { name: 'CityCare Multispeciality Hospital', is_active: true, bed_capacity: 220 },
    create: { name: 'CityCare Multispeciality Hospital', code: 'CCH-DEMO', address: '12 Residency Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560025', country: 'India', phone: '+91 80 4567 8900', email: 'care@citycare.demo', website: 'www.citycare.demo', nabh_number: 'NABH/CCH/2026/118', gstin: '29AACCC1234M1ZX', bed_capacity: 220, license_type: 'PROFESSIONAL', license_end: day(365), modules_enabled: ['PATIENTS','APPOINTMENTS','TELEMEDICINE','EMR','BEDS','ICU','OT','EMERGENCY','RADIOLOGY','PHARMACY','BILLING','INVENTORY','STAFF','AMBULANCE','DIETARY','MORTUARY','COMPLIANCE','COMMUNICATION','ANALYTICS'] }
  });
  const admin = await prisma.user.upsert({ where: { email: 'admin@citycare.demo' }, update: { password: hash, hospital_id: hospital.id, role: 'HOSPITAL_ADMIN', is_active: true }, create: { hospital_id: hospital.id, first_name: 'Aarav', last_name: 'Mehta', email: 'admin@citycare.demo', password: hash, role: 'HOSPITAL_ADMIN', designation: 'Hospital Administrator', phone: '+91 90000 10001' } });

  const deptDefs = [['Cardiology','CARD','1','201'],['Emergency Medicine','ER','G','101'],['General Medicine','MED','2','202'],['Orthopaedics','ORTHO','3','301'],['Pathology & Diagnostics','LAB','G','115'],['Critical Care','ICU','4','401']];
  const departments = {};
  for (const [name, code, floor, ext] of deptDefs) departments[code] = await prisma.department.upsert({ where: { hospital_id_code: { hospital_id: hospital.id, code } }, update: { name, floor, phone_ext: ext }, create: { hospital_id: hospital.id, name, code, floor, phone_ext: ext } });

  const staffDefs = [['Rohan','Sharma','rohan.sharma@citycare.demo','DOCTOR','Senior Consultant · Cardiology','CARD'],['Isha','Nair','isha.nair@citycare.demo','DOCTOR','Consultant · General Medicine','MED'],['Vikram','Patil','vikram.patil@citycare.demo','DOCTOR','Consultant · Orthopaedics','ORTHO'],['Neha','Kapoor','neha.kapoor@citycare.demo','DOCTOR','Consultant · Emergency Medicine','ER'],['Meera','Joseph','meera.joseph@citycare.demo','NURSE','Nursing Superintendent','ICU'],['Kabir','Rao','kabir.rao@citycare.demo','NURSE','Staff Nurse · Critical Care','ICU'],['Ananya','Das','ananya.das@citycare.demo','RECEPTIONIST','Front Office Lead','MED'],['Sanjay','Kulkarni','sanjay.kulkarni@citycare.demo','LAB_TECHNICIAN','Lab Supervisor','LAB'],['Pooja','Menon','pooja.menon@citycare.demo','PHARMACIST','Chief Pharmacist','MED'],['Nitin','Bose','nitin.bose@citycare.demo','ACCOUNTANT','Revenue Manager','MED']];
  const staff = {};
  for (const [first,last,email,role,designation,code] of staffDefs) { const u = await prisma.user.upsert({ where: { email }, update: { hospital_id: hospital.id, password: hash, is_active: true }, create: { hospital_id: hospital.id, first_name: first, last_name: last, email, password: hash, role, designation, department_id: departments[code].id, phone: '+91 90000 ' + String(10000 + Object.keys(staff).length) } }); staff[email] = u; if (role === 'DOCTOR') await prisma.doctorProfile.upsert({ where: { user_id: u.id }, update: {}, create: { user_id: u.id, specialization: designation.split('·')[1]?.trim(), qualification: 'MBBS, MD', registration_no: 'KMC-' + u.id.slice(0, 6).toUpperCase(), experience_years: 12, consultation_fee: 850, follow_up_fee: 500, teleconsult_fee: 700, bio: 'Compassionate clinician focused on evidence-based care.' } }); }
  const doctors = staffDefs.filter(x => x[3] === 'DOCTOR').map(x => staff[x[2]]);

  const names = [['Priya','Iyer','FEMALE','A_POS','Bengaluru'],['Rahul','Verma','MALE','O_POS','Mysuru'],['Kavya','Reddy','FEMALE','B_POS','Bengaluru'],['Arjun','Malhotra','MALE','AB_POS','Tumakuru'],['Sahana','Kumar','FEMALE','O_NEG','Bengaluru'],['Dev','Shah','MALE','A_NEG','Hosur'],['Nandini','Rao','FEMALE','B_POS','Bengaluru'],['Imran','Khan','MALE','O_POS','Bengaluru'],['Lakshmi','Nair','FEMALE','A_POS','Mandya'],['Aditya','Joshi','MALE','AB_POS','Bengaluru'],['Maya','Thomas','FEMALE','O_POS','Bengaluru'],['Vivek','Sinha','MALE','B_POS','Kolar']];
  const patients = [];
  for (let i=0;i<names.length;i++) { const [first,last,gender,blood,city] = names[i]; patients.push(await prisma.patient.upsert({ where: { uhid: `CCH-${String(10001+i).padStart(6,'0')}` }, update: { created_at: i < 4 ? day(0, 8+i) : ago(i+2) }, create: { hospital_id: hospital.id, uhid: `CCH-${String(10001+i).padStart(6,'0')}`, first_name:first,last_name:last,gender,blood_group:blood,dob:new Date(1970+i, i%12, 8+i),phone:'+91 98'+String(10000000+i),email:`${first.toLowerCase()}.${last.toLowerCase()}@mail.demo`,address:`${12+i} Lake View Apartments`,city,state:'Karnataka',pincode:'5600'+String(10+i),occupation:i%2?'Software Engineer':'Business Professional',marital_status:i%3?'MARRIED':'SINGLE',barcode_data:`CCH-${10001+i}` } })); }

  const beds = [];
  for (const [code, count, type] of [['MED',12,'GENERAL'],['CARD',8,'SEMI_PRIVATE'],['ORTHO',8,'PRIVATE'],['ICU',6,'ICU'],['ER',4,'HDU']]) for (let i=1;i<=count;i++) beds.push(await prisma.bed.upsert({ where: { hospital_id_ward_bed_no: { hospital_id:hospital.id, ward:departments[code].name, bed_no:`${code}-${String(i).padStart(2,'0')}` } }, update: { status: i <= Math.ceil(count*.55) ? 'OCCUPIED' : i === count ? 'CLEANING' : 'AVAILABLE' }, create: { hospital_id:hospital.id, ward:departments[code].name, department_id:departments[code].id, room_no:`${Math.ceil(i/2)}${i%2?'A':'B'}`, bed_no:`${code}-${String(i).padStart(2,'0')}`, floor:departments[code].floor, bed_type:type, status:i <= Math.ceil(count*.55) ? 'OCCUPIED' : i === count ? 'CLEANING' : 'AVAILABLE', rate_per_day:type==='ICU'?8500:type==='PRIVATE'?4500:2500, features:type==='ICU'?['Ventilator','Central Monitor']:['Oxygen Outlet'] } }));
  const occupiedBeds = beds.filter(b => b.status === 'OCCUPIED');
  const admissions = []; for (let i=0;i<8;i++) admissions.push(await prisma.admission.create({ data:{ hospital_id:hospital.id,patient_id:patients[i].id,bed_id:occupiedBeds[i].id,admitting_doctor_id:doctors[i%doctors.length].id,admission_type:i%3===0?'EMERGENCY':'ELECTIVE',admission_date:i<3?day(-i,7+i):ago(i+1),provisional_diagnosis:['Acute coronary syndrome','Community acquired pneumonia','Type 2 diabetes with infection','Fracture neck of femur'][i%4],final_diagnosis:i%3===0?null:['Hypertension with dyslipidaemia','Viral pneumonia'][i%2],status:'ADMITTED',estimated_los:3+i } }));
  for (let i=0;i<12;i++) { const p=patients[i], doctor=doctors[i%doctors.length]; await prisma.appointment.create({ data:{ hospital_id:hospital.id,patient_id:p.id,doctor_id:doctor.id,department_id:[departments.CARD.id,departments.MED.id,departments.ORTHO.id][i%3],token_no:`${String(i+1).padStart(2,'0')}`,appointment_date: i<7?day(0,8+i):day(i%5+1,10),slot_time:`${String(8+i%8).padStart(2,'0')}:${i%2?'30':'00'}`,type:i===5?'TELECONSULT':'REGULAR',status:i<2?'IN_CONSULTATION':i<5?'CHECKED_IN':i===6?'NO_SHOW':'BOOKED',priority:i===2?'URGENT':'NORMAL',chief_complaint:['Chest discomfort','Persistent cough','Knee pain','Routine diabetes review'][i%4],fee:850,checked_in_at:i<5?day(0,8+i):null } }); }
  for (let i=0;i<6;i++) { const p=patients[i], doctor=doctors[i%doctors.length]; await prisma.eMRNote.create({ data:{ patient_id:p.id,doctor_id:doctor.id,visit_date:day(-i,9),subjective:'Patient reports improvement since last visit.',objective:'Alert, oriented. Examination within expected limits.',assessment:['Hypertension','Type 2 diabetes mellitus','Stable angina'][i%3],plan:'Continue current plan. Review in 2 weeks.',icd10_codes:['I10','E11.9'],encounter_type:i<2?'IPD':'OPD' } }); await prisma.vitals.create({ data:{ patient_id:p.id,recorded_by:staff['meera.joseph@citycare.demo'].id,temperature:36.7,pulse:72+i,bp_systolic:124+i,bp_diastolic:78,spo2:97,respiratory_rate:18,weight:62+i,bmi:22.4,recorded_at:day(-i,9),encounter_type:'OPD' } }); }
  await prisma.prescription.create({ data:{ patient_id:patients[0].id,doctor_id:doctors[0].id,prescribed_at:day(0,9),notes:'Take after meals',items:{ create:[{drug_name:'Amlodipine',generic_name:'Amlodipine',strength:'5 mg',form:'Tablet',dose:'1 tablet',frequency:'Once daily',duration:'30 days',route:'Oral',quantity:30},{drug_name:'Atorvastatin',generic_name:'Atorvastatin',strength:'20 mg',form:'Tablet',dose:'1 tablet',frequency:'At night',duration:'30 days',route:'Oral',quantity:30}] } } });
  const stack = await prisma.medicineStack.upsert({ where:{hospital_id_name:{hospital_id:hospital.id,name:'Hypertension Starter Pack'}}, update:{}, create:{hospital_id:hospital.id,name:'Hypertension Starter Pack',condition:'Hypertension',description:'Standard first-line OPD pack'} }); await prisma.medicineStackItem.create({ data:{stack_id:stack.id,drug_name:'Amlodipine',generic_name:'Amlodipine',strength:'5 mg',form:'Tablet',dose:'1 tablet',frequency:'Once daily',duration:'30 days',route:'Oral',quantity:30} });

  const tests=[['Complete Blood Count','CBC','HAEMATOLOGY','Blood','g/dL','12-16',450],['HbA1c','HBA1C','BIOCHEMISTRY','Blood','%','4-6',650],['Lipid Profile','LIPID','BIOCHEMISTRY','Blood','mg/dL','<200',900],['Thyroid Profile','TFT','HORMONES','Blood','mIU/L','0.4-4.0',800]]; const testRows=[]; for(const [name,code,category,sample,unit,ref,price] of tests) testRows.push(await prisma.labTest.upsert({where:{hospital_id_name:{hospital_id:hospital.id,name}},update:{price},create:{hospital_id:hospital.id,name,code,category,sample_type:sample,unit,ref_range:ref,price}}));
  for(let i=0;i<6;i++){await prisma.labOrder.create({data:{hospital_id:hospital.id,order_no:`LAB-${now.getFullYear()}-${String(301+i).padStart(4,'0')}`,patient_id:patients[i].id,ordered_by:doctors[i%3].id,is_stat:i===1,status:i<2?'PROCESSING':i<4?'RESULTED':'REPORTED',sample_type:'Blood',collected_at:day(-i,8),reported_at:i>3?day(-i,16):null,items:{create:testRows.slice(0,i%3+1).map((t,j)=>({test_name:t.name,test_code:t.code,category:t.category,result:i>1?(j?'128':'13.4'):null,unit:t.unit,ref_range:t.ref_range,is_abnormal:j===0&&i%2===0}))}}});}
  for(let i=0;i<4;i++) await prisma.radiologyOrder.create({data:{hospital_id:hospital.id,study_no:`RAD-${String(701+i)}`,patient_id:patients[i].id,ordered_by:doctors[i%3].id,modality:['XRAY','CT','USG','ECHO'][i],body_part:['Chest','Head','Abdomen','Heart'][i],clinical_info:'Clinical evaluation and follow-up',is_stat:i===1,status:i<2?'REPORTED':'ORDERED',scheduled_at:day(i+1,11),report:i<2?'No acute abnormality detected.':'',impression:i<2?'Stable study':'Awaiting scan'}});

  const meds=[['Paracetamol 500 mg','Calpol','ANALGESIC',120,20],['Amoxicillin 500 mg','Mox','ANTIBIOTIC',0,25],['Amlodipine 5 mg','Amlong','ANTIHYPERTENSIVE',68,20],['Metformin 500 mg','Glycomet','ANTIDIABETIC',240,30],['Enoxaparin 40 mg','Clexane','ANTICOAGULANT',9,10],['Pantoprazole 40 mg','Pantocid','ANTACID',145,20]]; const medRows=[]; for(const [generic,brand,category,stock,min] of meds){const item=await prisma.pharmacyItem.create({data:{hospital_id:hospital.id,generic_name:generic,brand_name:brand,category,form:'Tablet',strength:generic.split(' ').slice(-2).join(' '),unit:'tablet',pack_unit:'strip',units_per_pack:10,current_stock:stock,min_stock_level:min,max_stock_level:500,reorder_quantity:100,rack_location:`R-${medRows.length+1}`}}); medRows.push(item); await prisma.drugBatch.create({data:{item_id:item.id,batch_no:`CCH${2026}${medRows.length}A`,mfg_date:ago(90),expiry_date:day(300),quantity_in:stock+50,quantity_rem:stock,mrp:120,selling_price:110,cost_price:80,supplier:'MedSupply India'}});}
  const supplier=await prisma.supplier.create({data:{hospital_id:hospital.id,name:'MedSupply India Pvt Ltd',contact:'Ritesh Menon',phone:'+91 80 4455 2211',email:'orders@medsupply.demo',gstin:'29AABCM4432Q1ZA',drug_license:'KA/DRUG/11882'}}); await prisma.purchaseOrder.create({data:{hospital_id:hospital.id,po_no:'PO-2026-0048',supplier_id:supplier.id,status:'PARTIAL_RECEIVED',total_amount:48500,ordered_at:ago(4),items:{create:[{item_name:'Amlodipine 5 mg',quantity:500,unit_price:3.4},{item_name:'IV Cannula 20G',quantity:300,unit_price:12}]}}});
  const bill=await prisma.bill.create({data:{hospital_id:hospital.id,bill_no:'CCH-OPD-260818',patient_id:patients[0].id,type:'OPD',status:'PARTIAL_PAID',subtotal:1850,total_amt:1850,paid_amt:1000,due_amt:850,items:{create:[{category:'Consultation',description:'Specialist consultation',quantity:1,unit_price:850,total:850},{category:'Diagnostics',description:'Lipid Profile',quantity:1,unit_price:900,total:900}]}}}); await prisma.payment.create({data:{bill_id:bill.id,amount:1000,mode:'UPI',reference_no:'UPI-CCH-8112',paid_at:day(0,10),received_by:admin.id}});
  for(let i=1;i<5;i++){const b=await prisma.bill.create({data:{hospital_id:hospital.id,bill_no:`CCH-IPD-2608${10+i}`,patient_id:patients[i].id,admission_id:admissions[i].id,type:'IPD_INTERIM',status:i%2?'PAID':'GENERATED',subtotal:6500+i*700,total_amt:6500+i*700,paid_amt:i%2?6500+i*700:0,due_amt:i%2?0:6500+i*700,items:{create:[{category:'Room',description:'In-patient care charges',quantity:2,unit_price:2500,total:5000},{category:'Doctor',description:'Consultant visit',quantity:2,unit_price:750,total:1500}]}}}); if(i%2) await prisma.payment.create({data:{bill_id:b.id,amount:6500+i*700,mode:i===1?'CASH':'INSURANCE_CASHLESS',paid_at:ago(i),received_by:admin.id}});}

  const invDefs=[['Surgical Gloves','CONSUMABLE','box',420,100,'Central Store'],['IV Cannula 20G','CONSUMABLE','piece',85,120,'Central Store'],['ECG Electrodes','CARDIOLOGY','pack',24,10,'Cardiology Store'],['Oxygen Mask','EMERGENCY','piece',76,20,'ER Store']]; for(const [name,category,unit,stock,min,location] of invDefs){const it=await prisma.inventoryItem.create({data:{hospital_id:hospital.id,name,code:'INV-'+(900+invDefs.indexOf(invDefs.find(x=>x[0]===name))),category,unit,current_stock:stock,min_level:min,location}}); await prisma.inventoryTransaction.create({data:{item_id:it.id,type:'RECEIPT',quantity:stock+100,reference:'GRN-2026-072',done_by:admin.id,created_at:ago(2)}});}
  for(const [name,category,dept] of [['CT Scanner','Imaging Equipment',departments.LAB.id],['Ventilator V-500','Critical Care',departments.ICU.id],['Digital X-Ray','Imaging Equipment',departments.LAB.id]]) await prisma.asset.create({data:{hospital_id:hospital.id,asset_tag:'AST-'+name.slice(0,3).toUpperCase()+Math.floor(Math.random()*900+100),name,category,make:'MediTech',model:'Pro Series',location:'Diagnostics Block',department_id:dept,purchase_date:ago(800),purchase_cost:category==='Critical Care'?1850000:420000,status:'ACTIVE',next_service:day(35)}});
  const room=await prisma.oTRoom.create({data:{hospital_id:hospital.id,name:'OT-1 · Main Theatre',status:'IN_USE',features:['Laminar Flow','C-Arm','Anaesthesia Workstation']}}); await prisma.oTRoom.create({data:{hospital_id:hospital.id,name:'OT-2 · Day Care',status:'AVAILABLE',features:['Endoscopy','Day Care']}}); await prisma.oTRecord.create({data:{hospital_id:hospital.id,ot_room_id:room.id,patient_id:patients[3].id,admission_id:admissions[3].id,procedure:'Open Reduction Internal Fixation',diagnosis:'Fracture neck of femur',surgery_type:'ELECTIVE',scheduled_start:day(0,11),scheduled_end:day(0,14),surgeon_id:doctors[2].id,anesthetist_id:doctors[1].id,status:'IN_PROGRESS',anesthesia_type:'Spinal',admit_after_surgery:true}});
  await prisma.emergencyCase.createMany({data:[{hospital_id:hospital.id,case_no:'ER-260818-001',patient_id:patients[1].id,chief_complaint:'Acute chest pain with sweating',triage_level:'RED',arrival_time:day(0,8),triage_time:day(0,8),doctor_time:day(0,8),doctor_id:doctors[0].id,status:'ACTIVE',notes:'ECG initiated; cath lab on standby'},{hospital_id:hospital.id,case_no:'ER-260818-002',patient_id:patients[5].id,chief_complaint:'Road traffic accident',triage_level:'ORANGE',arrival_time:day(0,9),triage_time:day(0,9),doctor_id:doctors[2].id,status:'ACTIVE'},{hospital_id:hospital.id,case_no:'ER-260817-003',patient_id:patients[7].id,chief_complaint:'Fever and dehydration',triage_level:'YELLOW',arrival_time:ago(1,16),status:'ADMITTED'}]});
  for(const user of [...doctors,staff['meera.joseph@citycare.demo'],staff['kabir.rao@citycare.demo']]) await prisma.shiftRoster.create({data:{hospital_id:hospital.id,user_id:user.id,date:day(0),shift:user.role==='DOCTOR'?'MORNING':'NIGHT',ward:user.role==='DOCTOR'?'OPD':'ICU',status:'PRESENT'}});
  const amb=await prisma.ambulance.create({data:{hospital_id:hospital.id,vehicle_no:'KA-01-EM-4521',type:'ALS',status:'ON_CALL',last_location:'Richmond Circle',fuel_level:74}}); await prisma.ambulance.create({data:{hospital_id:hospital.id,vehicle_no:'KA-01-EM-4522',type:'BLS',status:'AVAILABLE',last_location:'Hospital Bay 2',fuel_level:92}}); await prisma.ambulanceTrip.create({data:{ambulance_id:amb.id,patient_id:patients[5].id,patient_name:'Dev Malhotra',pickup_address:'Outer Ring Road, Bengaluru',call_time:day(0,7),dispatch_time:day(0,7),pickup_time:day(0,8),status:'PICKED_UP',km_covered:14,paramedic_notes:'Spinal precautions maintained'}});
  for(let i=0;i<4;i++) await prisma.dietOrder.create({data:{patient_id:patients[i].id,admission_id:admissions[i].id,diet_type:['Diabetic','Cardiac','Soft Diet','High Protein'][i],restrictions:i===1?['Low sodium']:[],allergies:i===2?['Peanuts']:[],calories:1800-i*100,ordered_by:staff['meera.joseph@citycare.demo'].id,start_date:day(0),is_active:true}});
  await prisma.incident.create({data:{hospital_id:hospital.id,incident_no:'INC-2026-0087',type:'NEAR_MISS',severity:'MODERATE',description:'Look-alike medication pack identified during pharmacy verification.',location:'Inpatient Pharmacy',reported_by:staff['pooja.menon@citycare.demo'].id,status:'CAPA_PENDING',capa:'Double-check shelf labels and conduct team huddle.',capa_due:day(7)}});
  await prisma.mortuaryRecord.create({data:{hospital_id:hospital.id,body_tag:'MORG-260817-04',patient_id:patients[8].id,patient_name:'Lakshmi Nair',age:'74',gender:'FEMALE',dod:ago(1,22),cause_of_death:'Respiratory failure',storage_slot:'M-04',nok_name:'Suresh Nair',nok_phone:'+91 98765 43210',nok_relation:'Son',is_released:false}});
  await prisma.announcement.create({data:{hospital_id:hospital.id,title:'Monthly quality huddle · 4:30 PM',body:'All department leads are invited to review patient flow, lab TAT and safety indicators.',priority:'URGENT',target_roles:['HOSPITAL_ADMIN','DOCTOR','NURSE'],created_by:admin.id,expires_at:day(7)}}); await prisma.message.create({data:{hospital_id:hospital.id,from_user_id:doctors[0].id,to_user_id:staff['meera.joseph@citycare.demo'].id,content:'Cath lab checklist is ready for the ER chest pain case. Please confirm transfer readiness.',type:'ALERT'}});
  console.log(`Demo hospital ready: ${hospital.name}`); console.log('Login: admin@citycare.demo / ' + password); console.log('Staff accounts use the same password.');
}
main().catch(e=>{console.error('Demo seed failed:',e);process.exitCode=1}).finally(()=>prisma.$disconnect());
